name: Cypress Tests

on:
  workflow_dispatch:

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.12.0-chrome103-ff107
      options: --user 1001
    steps: 
      - name: Get code
        uses: actions/checkout@v4.1.7

      - name: Install dependencies 
        run: npm install 

      - name: Run E2E Tests
        run: node runner-electron.js
    env:
      TARGET_TOKEN_ELECTRON: ${{ secrets.TARGET_TOKEN_ELECTRON}}

# ===========    RODANDO GOOGLE CHROME    ===========
  cypress-chrome-tests:
    needs: cypress-electron-tests
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.12.0-chrome103-ff107
      options: --user 1001
    steps: 
      - name: Get code
        uses: actions/checkout@v4.1.7

      - name: Install dependencies 
        run: npm install 

      - name: Run E2E Tests
        run: node runner-chrome.js
    env:
      TARGET_TOKEN_CHROME: ${{ secrets.TARGET_TOKEN_CHROME }}

# ===========    RODANDO FIREFOX    ===========
  cypress-firefox-tests:
    needs: cypress-electron-tests
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.12.0-chrome103-ff107
      options: --user 1001
    steps: 
      - name: Get code
        uses: actions/checkout@v4.1.7

      - name: Install dependencies 
        run: npm install 

      - name: Run E2E Tests
        run: node runner-firefox.js
    env:
      TARGET_TOKEN_FIREFOX: ${{ secrets.TARGET_TOKEN_FIREFOX }}
